/** Tipos de notificação in-app (partilhados com o frontend). */
export const NotificationType = {
  WELCOME_BONUS: "WELCOME_BONUS",
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  PAYMENT_CONFIRMED: "PAYMENT_CONFIRMED",
  SESSION_REQUEST: "SESSION_REQUEST",
  SESSION_ACCEPTED: "SESSION_ACCEPTED",
  SESSION_REJECTED: "SESSION_REJECTED",
  SESSION_ENDED: "SESSION_ENDED",
  CONDUCTOR_JOINED: "CONDUCTOR_JOINED",
  CONDUCTOR_LINKED: "CONDUCTOR_LINKED",
  CONDUCTOR_UNLINKED: "CONDUCTOR_UNLINKED",
  CONDUCTOR_WELCOME: "CONDUCTOR_WELCOME",
  PAYOUT_CONFIRM: "PAYOUT_CONFIRM",
  PAYOUT_RECEIVED: "PAYOUT_RECEIVED",
  PAYOUT_COMPLETED: "PAYOUT_COMPLETED",
  PAYOUT_SCHEDULED: "PAYOUT_SCHEDULED",
  CONDUCTOR_WITHDRAW_REQUEST: "CONDUCTOR_WITHDRAW_REQUEST",
  CONDUCTOR_WITHDRAW_DECISION: "CONDUCTOR_WITHDRAW_DECISION",
  REFUND_REQUEST: "REFUND_REQUEST",
  REFUND_REJECTED: "REFUND_REJECTED",
  REFUND_AWAITING_DRIVER: "REFUND_AWAITING_DRIVER",
  REFUND_APPROVED: "REFUND_APPROVED",
  TRIP_PAYMENT_REQUEST: "TRIP_PAYMENT_REQUEST",
} as const;

export type NotificationTypeValue =
  (typeof NotificationType)[keyof typeof NotificationType];
